import { IsString, Length } from "class-validator";

/** Payload accepted by the legacy invite-code guild join endpoint. */
export class JoinGuildDto {
  /** Invite code generated by a guild owner or officer. */
  @IsString()
  @Length(10, 32)
  inviteCode!: string;
}
