import { ApiProperty } from "@nestjs/swagger";
import { IsString, Length } from "class-validator";

/** Payload accepted by the legacy invite-code guild join endpoint. */
export class JoinGuildDto {
  /** Invite code generated by a guild owner or officer. */
  @ApiProperty({ example: "ABCD1234EF", maxLength: 32, minLength: 10 })
  @IsString()
  @Length(10, 32)
  inviteCode!: string;
}
